//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntonioL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacione
    {
        public System.Guid id_calificacion { get; set; }
        public int id_videojuego { get; set; }
        public string nickname { get; set; }
        public decimal puntuacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public string usuario_actualizacion { get; set; }
    
        public virtual Videojuego Videojuego { get; set; }
    }
}
