//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntonioL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compania()
        {
            this.Videojuegos = new HashSet<Videojuego>();
        }
    
        public int id_compania { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public string usuario_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videojuego> Videojuegos { get; set; }
    }
}
