//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntonioL.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videojuego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videojuego()
        {
            this.Calificaciones = new HashSet<Calificacione>();
        }
    
        public int id_videojuego { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_compania { get; set; }
        public Nullable<int> anio_lanzamiento { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> puntaje_promedio { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public string usuario_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacione> Calificaciones { get; set; }
        public virtual Compania Compania { get; set; }
    }
}
